groups:
 - name: bcn-dotnet
   rules:
   - alert: DatabaseDown
     expr: absent(mssql_instance_local_time) == 1
     for: 1m
     labels:
      severity: critical
     annotations:
      summary: "database is down"