{
 "title": "dotnet BCN Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Time during which the app is in operation.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Elasticsearch number of documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_primary"
    }
   ]
  },
  {
   "title": "Elasticsearch Indices size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes)"
    }
   ]
  },
  {
   "title": "Domain Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "atoma_domain_events_count" }
   ]
  },
  {
   "title": "Domain Events Processed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "atoma_domain_events_processed_count"
    }
   ]
  },
  {
   "title": "Domain Events Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "atoma_domain_events_failed_count"
    }
   ]
  },
  {
   "title": "Hangfire jobs executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "hangfire_jobs_executed_count" }
   ]
  },
  {
   "title": "Hangfire jobs succeed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "hangfire_jobs_succeed_count" }
   ]
  },
  {
   "title": "Hangfire jobs failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "hangfire_jobs_failed_count" }
   ]
  },
  {
   "title": "HTTP number of requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_http_requests_total[5m]))"
    },
    {}
   ]
  },
  {
   "title": "HTTP request duration average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(dotnet_http_request_duration_milliseconds >= 0)"
    }
   ]
  },
  {
   "title": "NServiceBus Messages Rates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nservicebus_failure_total[5m]))",
     "legendFormat": "Failure rate"
    },
    {
     "expr": "avg(rate(nservicebus_success_total[5m]))",
     "legendFormat": "Fetch rate"
    },
    {
     "expr": "avg(rate(nservicebus_success_total[5m]))",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Rabbitmq queues",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_delivered_total"
    },
    {}
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100"
    }
   ]
  }
 ]
}