FROM grafana/grafana:5.2.2
COPY ./datasource.yml /etc/grafana/provisioning/datasources/datasource.yml
COPY ./dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml
COPY ./dashboard.json /etc/grafana/provisioning/dashboards/dashboard.json